##CMD will only run at the time of using docker run command
##RUN will only run at the time of using docker build command
FROM almalinux:9

RUN dnf install nginx -y

CMD [ "nginx", "-g", "daemon off;" ]
